# Generated by Django 5.2.6 on 2025-09-18 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CardapioItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('EN', 'Entrada'), ('PR', 'Prato Principal'), ('SO', 'Sobremesa')], max_length=2)),
                ('titulo', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('foto', models.ImageField(upload_to='cardapio/')),
            ],
        ),
        migrations.CreateModel(
            name='PromocaoEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('imagem', models.ImageField(upload_to='promocoes/')),
            ],
        ),
    ]
