# Generated by Django 5.2.6 on 2025-09-20 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurante', '0002_cardapioitem_preco'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(verbose_name='Avaliação')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='feedback/')),
            ],
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('foto', models.ImageField(upload_to='equipe/')),
            ],
        ),
    ]
