# Generated by Django 5.2.6 on 2025-09-20 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurante', '0003_feedbackcliente_funcionario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedbackcliente',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='historia/'),
        ),
    ]
