# Generated by Django 4.2.24 on 2025-09-20 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurante', '0003_feedbackcliente_funcionario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_cliente', models.CharField(max_length=100)),
                ('telefone', models.CharField(max_length=20)),
                ('data_reserva', models.DateField()),
                ('hora_reserva', models.TimeField()),
                ('numero_pessoas', models.IntegerField()),
                ('tipo_reserva', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='feedbackcliente',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='historia/'),
        ),
    ]
