# Generated by Django 5.2.6 on 2025-09-21 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurante', '0004_alter_feedbackcliente_foto'),
        ('restaurante', '0006_especialidades'),
    ]

    operations = [
    ]
