# Generated by Django 5.2.6 on 2025-09-23 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurante', '0007_merge_20250921_1635'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardapioitem',
            name='selecionado',
            field=models.BooleanField(default=False),
        ),
    ]
