# Generated by Django 5.2.6 on 2025-09-14 20:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='genero',
            options={'ordering': ['nome'], 'verbose_name': 'Gênero', 'verbose_name_plural': 'Gêneros'},
        ),
        migrations.AlterModelOptions(
            name='livro',
            options={'ordering': ['titulo'], 'verbose_name': 'Livro', 'verbose_name_plural': 'Livros'},
        ),
        migrations.RemoveField(
            model_name='livro',
            name='capa',
        ),
        migrations.AddField(
            model_name='livro',
            name='ano_publicacao',
            field=models.IntegerField(default=2000, verbose_name='Ano de Publicação'),
        ),
        migrations.AddField(
            model_name='livro',
            name='capa_image',
            field=models.ImageField(blank=True, null=True, upload_to='capas/', verbose_name='Capa do Livro'),
        ),
        migrations.AddField(
            model_name='livro',
            name='sinopse',
            field=models.TextField(default='Sem sinopse disponível', verbose_name='Sinopse'),
        ),
        migrations.AlterField(
            model_name='genero',
            name='nome',
            field=models.CharField(max_length=100, verbose_name='Nome do Gênero'),
        ),
        migrations.AlterField(
            model_name='livro',
            name='autor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblioteca.autor', verbose_name='Autor do Livro'),
        ),
        migrations.AlterField(
            model_name='livro',
            name='genero',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Livros', to='biblioteca.genero', verbose_name='Gênero'),
        ),
        migrations.AlterField(
            model_name='livro',
            name='titulo',
            field=models.CharField(max_length=200, verbose_name='Título do Livro'),
        ),
    ]
