# Generated by Django 5.2.6 on 2025-09-20 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0002_alter_genero_options_alter_livro_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livro',
            name='genero',
        ),
        migrations.AddField(
            model_name='livro',
            name='generos',
            field=models.ManyToManyField(related_name='livros', to='biblioteca.genero', verbose_name='Gêneros'),
        ),
        migrations.AlterField(
            model_name='autor',
            name='nome',
            field=models.CharField(max_length=255, verbose_name='Nome do Autor'),
        ),
    ]
