# Generated by Django 5.2.6 on 2025-09-20 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plano',
            options={'ordering': ['nome'], 'verbose_name': 'Plano', 'verbose_name_plural': 'Planos'},
        ),
        migrations.AddField(
            model_name='plano',
            name='ativo',
            field=models.BooleanField(default=True, verbose_name='Plano Ativo'),
        ),
        migrations.AddField(
            model_name='plano',
            name='descricao',
            field=models.TextField(blank=True, null=True, verbose_name='Descrição do Plano'),
        ),
        migrations.AddField(
            model_name='plano',
            name='duracao_meses',
            field=models.IntegerField(default=1, verbose_name='Duração do Plano (meses)'),
        ),
        migrations.AddField(
            model_name='plano',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='planos/', verbose_name='Imagem/Ícone do Plano'),
        ),
        migrations.AddField(
            model_name='plano',
            name='usuarios_max',
            field=models.IntegerField(default=1, verbose_name='Número máximo de usuários'),
        ),
        migrations.AlterField(
            model_name='plano',
            name='preco_inicial',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Preço Inicial'),
        ),
        migrations.AlterField(
            model_name='plano',
            name='preco_recorrente',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Preço Recorrente'),
        ),
        migrations.AlterField(
            model_name='plano',
            name='vantagens',
            field=models.ManyToManyField(blank=True, related_name='planos', to='planos.vantagem', verbose_name='Vantagens'),
        ),
    ]
