# Generated by Django 5.2.6 on 2025-09-20 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planos', '0002_alter_plano_options_plano_ativo_plano_descricao_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plano',
            name='descricao',
        ),
    ]
