# Generated by Django 5.2.6 on 2025-09-20 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planos', '0003_remove_plano_descricao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plano',
            name='nome',
            field=models.CharField(max_length=100, unique=True, verbose_name='Nome do Plano'),
        ),
    ]
